name: Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
      with:
        path: package
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ROS
      uses: suddrey-qut/setup-ros@master
      with:
        required-ros-distributions: noetic
    - name: Build Release
      uses: suddrey-qut/release-tools-ros@master
      id: build
      with:
        ros-distro: noetic      
    - name: Upload binaries to release
      uses: suddrey-qut/upload-release-action@master
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        files: ${{ steps.build.outputs.files }}
        tag: ${{ github.ref }}
    
        
